version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db
    restart: always

  db:
    image: mysql:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MYSQL_ROOT_PASSWORD: DBrootNagoreAS
      MYSQL_DATABASE: database


  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    depends_on:
      - db
    restart: always

  mailer:
    build: 
      context: ./mailer
      dockerfile: Dockerfile
    restart: always

volumes:
  db_data:

