apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mailer
  template:
    metadata:
      labels:
        component: mailer
    spec:
      containers:
      - name: mailer
        image: nagoregomez/mailer
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: mailer
spec:
  selector:
    component: mailer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
